sabibatbet/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import sabibatbet_login.urls as sabibatbet_login
import sabibatbet_profile.urls as sabibatbet_profile
import sabibatbet_menanggapi.urls as sabibatbet_menanggapi
import sabibatbet_forum.urls as sabibatbet_forum
from django.conf.urls import url, include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sabibatbet_login/', include(sabibatbet_login, namespace='sabibatbet-login')),
    url(r'^sabibatbet_profile/', include(sabibatbet_profile, namespace='sabibatbet-profile')),
    url(r'^sabibatbet_menanggapi/', include(sabibatbet_menanggapi, namespace='sabibatbet-menanggapi')),
    url(r'^sabibatbet_forum/', include(sabibatbet_forum, namespace='sabibatbet-forum'))
]

sabibatbet_forum/urls.py
from django.conf.urls import url
from .views import index, add_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-post/$', add_post, name='add-post'),
]

sabibatbet_login/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^add-session/$', add_session, name='add-session'),
    url(r'^remove-session/$', remove_session, name='remove-session'),
]

sabibatbet_menanggapi/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

sabibatbet_profile/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

sabibatbet_forum/models.py
from django.db import models
# # Create your models here.
class Post(models.Model):
    company_id = models.CharField('Company ID', max_length=200)
    content = models.TextField('Content', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

sabibatbet_login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.CharField('id', max_length=20, primary_key=True, )
    name = models.CharField('Name', max_length=200)
    company = models.CharField('company', max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

sabibatbet_menanggapi/models.py
from django.db import models
from sabibatbet_forum.models import Post
# Create your models here.
class Tanggapan(models.Model):
    post_id = models.ForeignKey(Post, null=True)
    name = models.CharField('Name', max_length=200)
    content = models.TextField('Content', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

sabibatbet_profile/models.py
from django.db import models

# Create your models here.

sabibatbet_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
import json
from .models import Post
from sabibatbet_login.models import User

# Create your views here.

response = {}
def index(request):
    if 'user_login' in request.session:
      user = User.objects.filter(id=request.session['user_login']).first()
      response['company_id'] = user.company
      response['posts'] = serializers.serialize('json',Post.objects.filter(company_id=user.company))
      html = 'forum.html'
      return render(request, html, response)
    else:
      return HttpResponseRedirect(reverse('sabibatbet-login:index'))

def add_post(request):
    if(request.method == "POST"):
        user = User.objects.filter(id=request.session['user_login']).first()
        company_id = user.company
        post = Post(company_id=company_id,content=request.POST['content'])
        post.save()
        return HttpResponseRedirect('/sabibatbet_forum/')

sabibatbet_login/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import User
from django.core import serializers
from sabibatbet_forum.models import Post
from sabibatbet_menanggapi.models import Tanggapan
# Create your views here.
response = {}

def index(request):
	response['posts'] = serializers.serialize('json',Post.objects.all())
	response['tanggapan'] = serializers.serialize('json',Tanggapan.objects.all())
	html = 'sabibatbet_login/home.html'
	return render(request, html, response)

@csrf_exempt
def add_session(request):
	if request.method == 'POST':
		name = request.POST['name']
		id = request.POST['id']
		company =request.POST['companyID']
		request.session['user_login']= id
		request.session['name'] = name
		try:
			user = User.objects.get(id = id)
		except Exception as e:
			user = User()
			user.id = id
			user.name = name
			user.company = company
			user.save()
		return HttpResponseRedirect(reverse('sabibatbet-login:index'))

def remove_session(request):
	request.session.flush()
	return HttpResponseRedirect(reverse('sabibatbet-login:index'))

sabibatbet_menanggapi/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Tanggapan
from sabibatbet_forum.models import Post
from sabibatbet_login.models import User

# Create your views here.
def index(request):
    if request.method == "POST":
      company_id = "-1"
      if 'user_login' in request.session:
        user = User.objects.filter(id=request.session['user_login']).first()
        company_id = user.company
      post = Post.objects.filter(id=request.POST["post_id"]).first()
      tanggapan = Tanggapan(post_id=post, name=company_id, content=request.POST["content"])
      tanggapan.save()
      return HttpResponseRedirect('/sabibatbet_login/')

sabibatbet_profile/views.py
from django.shortcuts import render

# Create your views here.
response = {}

def index(request):
    html = 'sabibatbet_profile/sabibatbet_profile.html'
    return render(request, html, response)

sabibatbet_forum/templates/forum.html
{% extends "forum/layout/base.html" %}
{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="rata-tengah">
      <div class="judul">
        <h1 id="title"> Forum </h1>
      </div>
    </div>
    <div class="post-list"></div>
    <!-- {% for post in posts %}
      <p>{{ post.company_id }} - {{ post.content }}</p>
    {% endfor %} -->
    <form action="{% url 'sabibatbet-forum:add-post' %}" method="POST">
      {% csrf_token %}
      <textarea name="content"></textarea>
      <input type="submit" name="Submit" value="Submit">
    </form>
  </div>
  <script type="text/javascript">
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getCompanyProfile);
    }

    function getCompanyProfile() {
      IN.API.Raw("/companies/" + {{company_id}} + ":(name)?format=json")
        .method("GET")
        .result(function(response){
          var html = response["name"];
          $("#title").append(html);
        })
        .error(function(response){
          console.log(response);
        });
      var post_string = '{{posts|safe}}';
      var posts = JSON.parse(post_string);
      posts.forEach(function(post){
        IN.API.Raw("/companies/" + post.fields["company_id"] + ":(id,name,square-logo-url)?format=json")
        .method("GET")
        .result(function(response){
          console.log(response);
          var html = "<div>" + "<img src='" + response["squareLogoUrl"] + "'></img> " + post.fields["content"] + "</div><br>"
          $(".post-list").append(html);
        })
        .error(function(response){
          console.log(response);
        });
      })
    }

    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }

    // Remove profile data from page
    function removeProfileData(){
      window.location.assign("/sabibatbet_login/");
      $.ajax({
          method: "GET",
          url: '/sabibatbet_login/remove-session',
    });
    }

  </script>
</div>
<!-- <div class="container">
    <div class="row">
        <div class="[ col-xs-12 col-sm-offset-1 col-sm-5 ]">
            <div class="[ panel panel-default ] panel-google-plus">
                <div class="panel-heading">
                    <img class="[ img-circle pull-left ]" src="https://lh3.googleusercontent.com/-CxXg7_7ylq4/AAAAAAAAAAI/AAAAAAAAAQ8/LhCIKQC5Aq4/s46-c-k-no/photo.jpg" alt="Mouse0270" />
                    <h3>{{ company_id }}</h3>
                    <h5><span>Shared publicly</span> - <span>{{ post.created_at }}</span> </h5>
                </div>
                <div class="panel-body">
                  {% for post in posts %}
                    <p>{{ post.content }}</p>
                  {% endfor %}
                </div>
                <div>
                  <form action="{% url 'sabibatbet-forum:add-post' %}" method="POST">
                    {% csrf_token %}
                    <textarea name="content"></textarea>
                    <input type="submit" name="Submit" value="Submit">
                  </form>
                </div>
                <div class="panel-footer">
                    <button type="button" class="[ btn btn-default ]">+1</button>
                    <button type="button" class="[ btn btn-default ]">
                        <span class="[ glyphicon glyphicon-share-alt ]"></span>
                    </button>
                    <div class="input-placeholder">Add a comment...</div>
                </div>
                <div class="panel-google-plus-comment">
                    <img class="img-circle" src="https://lh3.googleusercontent.com/uFp_tsTJboUY7kue5XAsGA=s46" alt="User Image" />
                    <div class="panel-google-plus-textarea">
                        <textarea rows="4"></textarea>
                        <button type="submit" class="[ btn btn-success disabled ]">Post comment</button>
                        <button type="reset" class="[ btn btn-default ]">Cancel</button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div> -->


{% endblock %}

sabibatbet_forum/templates/forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE HTML>
<html lang ="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Statistics">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">\
    <link rel="stylesheet" type="text/css" href="{% static 'css/sabibatbet_forum.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
    <link href="https://fonts.googleapis.com/css?family=Orbitron:900" rel="stylesheet">
    <link rel="shortcut icon" href="https://vignette3.wikia.nocookie.net/campcamp/images/e/e7/LI-favicon.png/revision/latest?cb=20160720055853" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'js/sabibatbet_forum.js' %}"></script>
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   816mxerpb74tkq
    onLoad:    onLinkedInLoad
    authorize: true
    </script>
    <title>
        {% block title %} SABIBATBET {% endblock %}
    </title>
</head>
<body>
  <header>
    {% block header %}
    {% include "sabibatbet_login/partials/header.html" %}
    {% endblock %}
  </header>
  <content>
    {% block content %}
    {% endblock %}
  </content>
  <footer>
    {% block footer %}
    {% include "forum/partials/footer.html" %}
    {% endblock %}
  </footer>
</body>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script src="https://code.jquery.com/qunit/qunit-2.4.1.js"></script>
</html>

sabibatbet_forum/templates/forum/partials/footer.html
<div class="footer">
      <div class="container">
        <p class="text-muted">&copy; 2017 ntaps sabeb sabibatbet.</p>
      </div>
</div>

sabibatbet_forum/templates/forum/partials/header.html
<div class="navbar navbar-inverse navbar-twitch" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">
				<span class="small-nav"></span>
				<span class="logo"></span>
				<span class="full-nav"> Keling </span>
			</a>
		</div>
		<div class="">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="#">
						<span class="small-nav" data-toggle="tooltip" data-placement="right" title="Home">
							<span class="glyphicon glyphicon-home"></span>
						</span>
						<span class="full-nav"> Home </span>
					</a>
				</li>
				<li>
					<a href="#about-us">
						<span class="small-nav" data-toggle="tooltip" data-placement="right" title="Profile">
							<span class="fa fa-users"></span>
						</span>
						<span class="full-nav"> Profile </span>
					</a>
				</li>
				<li>
					<a href="#contact-us">
						<span class="small-nav" data-toggle="tooltip" data-placement="right" title="Forum">
							<span class="glyphicon glyphicon-comment"></span>
						</span>
						<span class="full-nav"> Forum </span>
					</a>
				</li>
				<br>
				<br>
				<li>
					<a href="#logout">
						<span class="small-nav" data-toggle="tooltip" data-placement="right" title="Logout">
							<span class="glyphicon glyphicon-off"></span>
						</span>
						<span class="full-nav"> Logout </span>
					</a>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</div>
<button type="button" class="btn btn-default btn-xs navbar-twitch-toggle">
	<span class="glyphicon glyphicon-chevron-right nav-open"></span>
	<span class="glyphicon glyphicon-chevron-left nav-close"></span>
</button>

sabibatbet_login/templates/sabibatbet_login/home.html
{% extends "sabibatbet_login/layout/base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    <div class="rata-tengah">
      <div class="judul">
        <h1> Welcome to Keling</h1>
        <script type="in/Login"></script>
      </div>
      <h3> Forum Lowongan Kerja</h2>
    </div>
    <div class="post-list"></div>
  </div>
</div>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
        IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address").result(displayProfileData).error(onError);
    }

    function displayProfileData(data){
        var user = data.values[0];
        var id = user.id;
        console.log(id);
        IN.API.Raw("/companies?format=json&is-company-admin=true")
        .method("GET")
        .result(function(response){
          console.log(response.values[0].id)
          getCompanyData(response.values[0].id)
          $.ajax({
            method : "POST",
            url : '/sabibatbet_login/add-session/',
            data : {
              name: user.firstName+" "+user.lastName,
              id:id,
              companyID: response.values[0].id,
              csrfmiddlewaretoken : '{{ csrf_token }}'
            },
            success : showDetailPosts,
            error : function (error){
            }
          });
        });
        // $("#gambar").append('<img src="'+user.pictureUrl+'"class="img-circle">');
        $("#tempat").append('<button class="btn btn-primary">Company Profile </button>'+'<br>');
        $("#logout").append("<button class='btn btn-danger' onClick='logout()'>Logout</button>");
        console.log(data);
        console.log();
        // $("#name").append(
        //   '<p>'+'Logged in as '+user.firstName+' '+user.lastName+'</p>'+
        //   '<button class="btn btn-primary delete">Company Profile</button>');
        // document.getElementById('profileData').style.display = 'block';
    }

    function showDetailPosts() {
      var post_string = '{{posts|safe}}';
      var posts = JSON.parse(post_string);
      posts.forEach(function(post){
        IN.API.Raw("/companies/" + post.fields["company_id"] + ":(id,name,square-logo-url)?format=json")
        .method("GET")
        .result(function(response){
          var html = "<div>" + "<img src='" + response["squareLogoUrl"] + "'></img> " + post.fields["content"] + "</div><div id='" + post["pk"] + "-comment'></div>"
          $(".post-list").append(html);
          var tanggapan_string = '{{ tanggapan|safe }}';
          var tanggapans = JSON.parse(tanggapan_string);
          tanggapans.forEach(function(tanggapan){
            if(tanggapan.fields["post_id"] == post["pk"]) {
                var html_comment = "<div style='padding-left:10px; padding-top:5px'>" + "(" + tanggapan.fields["name"] + ") " + tanggapan.fields["content"] + "</div>";
                $("#"+post["pk"]+"-comment").append(html_comment)
            }
          })
          html = "<br><div>" +
                "<form action='/sabibatbet_menanggapi/' method='POST'>" +
                "{%csrf_token%}" +
                "<input type='hidden' name='post_id' value='"+
                post["pk"] +
                "'>" +
                "<textarea name='content'></textarea>" +
                "<input type='submit'>" +
                "</div><hr>"
          $("#"+post["pk"]+"-comment").append(html);
        })
        .error(function(response){
          console.log(response);
        });
      })
    }

    // Use the API call wrapper to request the company's profile data
    function getCompanyData(id) {
        // Masukin ID company lau
        var cpnyID = id;
        localStorage.setItem('companyId', cpnyID);
        console.log(localStorage.getItem('companyId'));
        IN.API.Raw("/companies/" + cpnyID + ":(id,name,ticker,description)?format=json")
          .method("GET")
          .result(displayCompanyData)
          .error(onError);
    }

    function displayCompanyData(data){
        // To do
    }
    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }

    // Remove profile data from page
    function removeProfileData(){
      window.location.assign("/sabibatbet_login/");
      $.ajax({
          method: "GET",
          url: '/sabibatbet_login/remove-session',
    });
    }

</script>
<!-- <div class="container">
    <div class="row">
        <div class="[ col-xs-12 col-sm-offset-0 col-sm-5 ]">
            <div class="[ panel panel-default ] panel-google-plus">
                <div class="panel-heading">
                    <img class="[ img-circle pull-left ]" src="https://lh3.googleusercontent.com/-CxXg7_7ylq4/AAAAAAAAAAI/AAAAAAAAAQ8/LhCIKQC5Aq4/s46-c-k-no/photo.jpg" alt="Mouse0270" />
                    <h3>{{ company_id }}</h3>
                    <h5><span>Dummy</span> </h5>
                </div>
                <div class="panel-body">
                  {% for post in posts %}
                    <p>{{ post.content }}</p>
                  {% endfor %}
                </div>
                <div class="panel-footer">
                    <button type="button" class="[ btn btn-default ]">+1</button>
                    <button type="button" class="[ btn btn-default ]">
                        <span class="[ glyphicon glyphicon-share-alt ]"></span>
                    </button>
                    <div class="input-placeholder">Add a comment...</div>
                </div>
                <div class="panel-google-plus-comment">
                    <img class="img-circle" src="https://lh3.googleusercontent.com/uFp_tsTJboUY7kue5XAsGA=s46" alt="User Image" />
                    <div class="panel-google-plus-textarea">
                        <textarea rows="4"></textarea>
                        <button type="submit" class="[ btn btn-success disabled ]">Post comment</button>
                        <button type="reset" class="[ btn btn-default ]">Cancel</button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div> -->


{% endblock %}

sabibatbet_login/templates/sabibatbet_login/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="SABIBATBET">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">\
    <link rel="stylesheet" type="text/css" href="{% static 'css/sabibatbet_forum.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
    <link href="https://fonts.googleapis.com/css?family=Orbitron:900" rel="stylesheet">
    <link rel="shortcut icon" href="https://vignette3.wikia.nocookie.net/campcamp/images/e/e7/LI-favicon.png/revision/latest?cb=20160720055853" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.2.js"></script>
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   816mxerpb74tkq
    onLoad:    onLinkedInLoad
    authorize: true
    </script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/sabibatbet_login.css' %}" />

    <title>
        {% block title %} SABIBATBET {% endblock %}
    </title>
</head>
<body>
<header>
    {% include "sabibatbet_login/partials/header.html" %}
</header>
<content>
    {% block content %}
    {% endblock %}
</content>
<footer>
    {% block footer %}
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- <script type="text/javascript" src="{% static 'js/sabibatbet_linkedin.js' %}"></script> -->
{% block javascript %}
{% endblock %}
</body>
</html>

sabibatbet_login/templates/sabibatbet_login/partials/header.html
<div class="navbar navbar-inverse navbar-twitch" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <span class="small-nav"></span>
                <span class="logo"></span>
                <span class="full-nav"> Keling </span>
            </a>
        </div>
        <div class="">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'sabibatbet-login:index' %}">
                        <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Home">
                            <span class="glyphicon glyphicon-home"></span>
                        </span>
                        <span class="full-nav"> Home </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'sabibatbet-profile:index' %}">
                        <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Profile">
                            <span class="fa fa-users"></span>
                        </span>
                        <span class="full-nav"> Profile </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'sabibatbet-forum:index' %}">
                        <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Forum">
                            <span class="glyphicon glyphicon-comment"></span>
                        </span>
                        <span class="full-nav"> Forum </span>
                    </a>
                </li>
                <br>
                <br>
                {% if request.session.user_login %}
                <li>
                    <a onclick="logout()">
                        <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Logout">
                            <span class="glyphicon glyphicon-off"></span>
                        </span>
                        <span class="full-nav"> Logout </span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<button type="button" class="btn btn-default btn-xs navbar-twitch-toggle">
    <span class="glyphicon glyphicon-chevron-right nav-open"></span>
    <span class="glyphicon glyphicon-chevron-left nav-close"></span>
</button>

sabibatbet_profile/templates/sabibatbet_profile/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
	<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    {% block css %}
    <!-- CSS TAROH DI APPS MASING2 AJA YA BUAT NYESUAIIN -->
    {% endblock %}
</head>

<body>
    <div class="desain_header">
      {% block header %}

      {% endblock %}
    </div>

    <content>
      {% block content %}
      {% endblock %}
    </content>

    <footer class="desain_footer">
      {% include "sabibatbet_profile/partials/footer.html" %}
    </footer>
</body>

<!-- Jquery n Bootstrap Script -->
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
{% block javascript %}
{% endblock %}
</html>

sabibatbet_profile/templates/sabibatbet_profile/partials/footer.html
<p class="text-center">Made with ♥ by Adi, Abi, Kinu, Daffa</p>